export default {
  "login": "andrew",
  "id": 1060,
  "node_id": "MDQ6VXNlcjEwNjA=",
  "avatar_url": "https://avatars.githubusercontent.com/u/1060?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/andrew",
  "html_url": "https://github.com/andrew",
  "followers_url": "https://api.github.com/users/andrew/followers",
  "following_url": "https://api.github.com/users/andrew/following{/other_user}",
  "gists_url": "https://api.github.com/users/andrew/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/andrew/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/andrew/subscriptions",
  "organizations_url": "https://api.github.com/users/andrew/orgs",
  "repos_url": "https://api.github.com/users/andrew/repos",
  "events_url": "https://api.github.com/users/andrew/events{/privacy}",
  "received_events_url": "https://api.github.com/users/andrew/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Andrew Nesbitt",
  "company": "@ecosyste-ms and @octobox ",
  "blog": "https://nesbitt.io",
  "location": "Bristol, UK",
  "email": null,
  "hireable": null,
  "bio": "Working on mapping the world of open source software @ecosyste-ms  and empowering developers with @octobox ",
  "twitter_username": "teabass",
  "public_repos": 309,
  "public_gists": 196,
  "followers": 3200,
  "following": 3260,
  "created_at": "2008-02-27T11:39:22Z",
  "updated_at": "2024-04-18T00:25:16Z"
};